FROM python:3

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY data ./data
COPY src ./src

CMD ["python", "src/webservice.py", "data/wirlernenonline.oeh3.h5", "data/wirlernenonline.oeh3.npy", "data/wirlernenonline.oeh3.pickle"]